spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthreport?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.jpcr.healthreportfinal.entity

swagger:
  enabled: true
